import type {
  EditorialRuleRecord,
  EditorialRuleSetRecord,
} from "../modules/editorial-rules/editorial-rule-record.ts";
import type {
  KnowledgeRecord,
  KnowledgeRevisionRecord,
} from "../modules/knowledge/knowledge-record.ts";
import type {
  GovernedContentModuleRecord,
  TemplateCompositionRecord,
} from "../modules/templates/template-record.ts";

export interface SeededGovernedKnowledgeBinding {
  bindingKind: "module_template" | "general_package" | "medical_package";
  bindingTargetId: string;
  bindingTargetLabel: string;
}

export interface SeededGovernedKnowledgeAssetDefinition {
  assetId: string;
  title: string;
  canonicalText: string;
  summary?: string;
  knowledgeKind: KnowledgeRecord["knowledge_kind"];
  status?: KnowledgeRevisionRecord["status"];
  moduleScope: KnowledgeRecord["routing"]["module_scope"];
  manuscriptTypes: KnowledgeRecord["routing"]["manuscript_types"];
  sections?: string[];
  riskTags?: string[];
  disciplineTags?: string[];
  bindings?: ReadonlyArray<SeededGovernedKnowledgeBinding>;
  createdAt: string;
  updatedAt?: string;
  revisionNo?: number;
}

const BASELINE_CREATED_AT = "2026-03-31T07:56:30.000Z";
const BASELINE_UPDATED_AT = "2026-03-31T08:06:00.000Z";

export const SEEDED_CLINICAL_STUDY_GENERAL_MODULES: readonly GovernedContentModuleRecord[] = [
  {
    id: "general-module-seeded-1",
    module_class: "general",
    name: "参考文献格式统一",
    category: "reference",
    manuscript_type_scope: ["clinical_study", "review"],
    execution_module_scope: ["editing", "proofreading"],
    applicable_sections: ["references"],
    summary: "统一参考文献的作者、题名、期刊、年份、卷期页码与标点写法。",
    guidance: ["作者、题名、期刊信息顺序保持规范。", "卷期页码与 DOI 写法按期刊要求统一。"],
    status: "published",
    created_at: BASELINE_CREATED_AT,
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "general-module-seeded-2",
    module_class: "general",
    name: "缩略语与术语首现释义",
    category: "terminology",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["screening", "editing", "proofreading"],
    applicable_sections: ["abstract", "introduction", "methods", "results", "discussion"],
    summary: "首现缩略语给出全称，并保持全文术语、缩略语和大小写写法一致。",
    guidance: ["首次出现时补充全称或中文释义。", "同一实体只保留一种标准写法。"],
    status: "published",
    created_at: "2026-03-31T07:57:00.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "general-module-seeded-3",
    module_class: "general",
    name: "作者单位与通讯作者前置信息",
    category: "front_matter",
    manuscript_type_scope: ["clinical_study", "review", "case_report"],
    execution_module_scope: ["editing", "proofreading"],
    applicable_sections: ["front_matter"],
    summary: "统一作者、单位、通讯作者、基金与脚注信息的前置信息块。",
    guidance: ["作者顺序与署名仅做核对，不自动改写。", "单位序号、通讯作者与基金标注保持一致。"],
    status: "published",
    created_at: "2026-03-31T07:57:15.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "general-module-seeded-4",
    module_class: "general",
    name: "摘要标签与关键词规范",
    category: "abstract_keywords",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["screening", "editing", "proofreading"],
    applicable_sections: ["abstract", "keywords"],
    summary: "统一摘要分标签、关键词数量、分隔符与中英文对应关系。",
    guidance: ["摘要标签使用统一口径。", "关键词数量、顺序与分隔符保持一致。"],
    status: "published",
    created_at: "2026-03-31T07:57:30.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "general-module-seeded-5",
    module_class: "general",
    name: "标题层级与章节顺序",
    category: "manuscript_structure",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["screening", "editing", "proofreading"],
    applicable_sections: ["body"],
    summary: "统一一级到三级标题层级，并校验临床研究主线章节顺序是否完整。",
    guidance: ["目标、方法、结果、结论与伦理信息需能在结构上定位。", "章节顺序异常时转人工复核。"],
    status: "published",
    created_at: "2026-03-31T07:57:45.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "general-module-seeded-6",
    module_class: "general",
    name: "三线表与表注格式",
    category: "table_format",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["editing", "proofreading"],
    applicable_sections: ["results"],
    summary: "统一三线表标题、列头、单位、统计学脚注与表注位置。",
    guidance: ["表题置于表上，表注置于表下。", "单位与统计学脚注要与列头及正文一致。"],
    evidence_level: "medium",
    risk_level: "medium",
    status: "published",
    created_at: "2026-03-31T07:58:00.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
];

export const SEEDED_CLINICAL_STUDY_MEDICAL_MODULES: readonly GovernedContentModuleRecord[] = [
  {
    id: "medical-module-seeded-1",
    module_class: "medical_specialized",
    name: "伦理声明核查",
    category: "ethics",
    manuscript_type_scope: ["clinical_study", "case_report"],
    execution_module_scope: ["screening", "editing", "proofreading"],
    applicable_sections: ["ethics", "methods", "back_matter"],
    summary: "核对伦理批件号、伦理委员会名称、知情同意与伦理豁免说明是否完整。",
    guidance: ["缺少批件号或知情同意时必须转人工复核。", "伦理豁免需要保留原始说明。"],
    evidence_level: "high",
    risk_level: "high",
    status: "published",
    created_at: "2026-03-31T07:58:15.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "medical-module-seeded-2",
    module_class: "medical_specialized",
    name: "终点与统计口径核对",
    category: "statistics",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["screening", "editing", "proofreading"],
    applicable_sections: ["abstract", "methods", "results", "discussion"],
    summary: "核对主要终点、分析人群、统计方法、P 值与结果表述是否前后一致。",
    guidance: ["主要终点名称必须在摘要、方法、结果之间一致。", "P 值、效应量与统计方法的口径需一致。"],
    evidence_level: "high",
    risk_level: "high",
    status: "published",
    created_at: "2026-03-31T07:58:30.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "medical-module-seeded-3",
    module_class: "medical_specialized",
    name: "研究设计与纳排标准核查",
    category: "study_design",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["screening", "editing"],
    applicable_sections: ["methods"],
    summary: "核对研究类型、纳入排除标准、分组方法、随访窗口与样本来源是否完整。",
    guidance: ["研究设计缺失时不允许自动补全医学事实。", "纳排标准与分组逻辑不完整时转人工复核。"],
    evidence_level: "high",
    risk_level: "high",
    status: "published",
    created_at: "2026-03-31T07:58:45.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "medical-module-seeded-4",
    module_class: "medical_specialized",
    name: "基线特征与分组一致性核查",
    category: "baseline_consistency",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["editing", "proofreading"],
    applicable_sections: ["methods", "results"],
    summary: "核对样本量、组别命名、基线特征表与正文引用的一致性。",
    guidance: ["样本量、组别名称与统计单位要在表文之间一致。", "涉及数值冲突时转人工复核。"],
    evidence_level: "high",
    risk_level: "medium",
    status: "published",
    created_at: "2026-03-31T07:59:00.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "medical-module-seeded-5",
    module_class: "medical_specialized",
    name: "不良事件与安全性表述核查",
    category: "safety",
    manuscript_type_scope: ["clinical_study"],
    execution_module_scope: ["screening", "proofreading"],
    applicable_sections: ["results", "discussion", "back_matter"],
    summary: "核对不良事件、安全性结果与风险提示表述是否完整且与结果一致。",
    guidance: ["严重不良事件、停药或失访信息不能被弱化。", "安全性结论缺少结果支撑时转人工复核。"],
    evidence_level: "high",
    risk_level: "high",
    status: "published",
    created_at: "2026-03-31T07:59:15.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
];

export const SEEDED_CLINICAL_STUDY_TEMPLATE_COMPOSITIONS: readonly TemplateCompositionRecord[] =
  [
  {
    id: "template-composition-seeded-1",
    name: "临床研究主线模板",
    manuscript_type: "clinical_study",
    general_module_ids: SEEDED_CLINICAL_STUDY_GENERAL_MODULES.map((item) => item.id),
    medical_module_ids: SEEDED_CLINICAL_STUDY_MEDICAL_MODULES.map((item) => item.id),
    execution_module_scope: ["screening", "editing", "proofreading"],
    notes: "覆盖临床研究主线在筛查、编辑、校对三段都需要复用的基础治理资产。",
    source_task_id: "extraction-task-seeded-1",
    source_candidate_ids: ["extraction-candidate-seeded-2"],
    version_no: 1,
    status: "published",
    created_at: "2026-03-31T07:59:30.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  {
    id: "template-composition-seeded-2",
    name: "病例报告精简模板",
    manuscript_type: "case_report",
    general_module_ids: ["general-module-seeded-1", "general-module-seeded-3"],
    medical_module_ids: ["medical-module-seeded-1"],
    execution_module_scope: ["editing", "proofreading"],
    notes: "优先覆盖伦理、署名与参考文献等高频结构。",
    version_no: 1,
    status: "published",
    created_at: "2026-03-31T07:59:45.000Z",
    updated_at: BASELINE_UPDATED_AT,
  },
  ];

export const SEEDED_CLINICAL_STUDY_KNOWLEDGE_ASSETS: readonly SeededGovernedKnowledgeAssetDefinition[] =
  [
  {
    assetId: "knowledge-general-reference-1",
    title: "参考文献著录顺序统一",
    canonicalText: "参考文献应按作者、题名、期刊、年份、卷期页码与 DOI 的标准顺序统一呈现。",
    summary: "默认绑定到通用包“参考文献格式统一”，供编辑与校对复用。",
    knowledgeKind: "rule",
    moduleScope: "editing",
    manuscriptTypes: ["clinical_study", "review"],
    sections: ["references"],
    bindings: [
      {
        bindingKind: "general_package",
        bindingTargetId: "general-module-seeded-1",
        bindingTargetLabel: "参考文献格式统一",
      },
    ],
    createdAt: "2026-03-31T07:56:40.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-general-abbreviation-1",
    title: "缩略语与术语首现释义规则",
    canonicalText: "英文缩略语首次出现时应补全称，并保证后文缩略语与术语写法一致。",
    summary: "默认绑定到通用包“缩略语与术语首现释义”，覆盖摘要、方法、结果与讨论中的高频术语问题。",
    knowledgeKind: "rule",
    moduleScope: "screening",
    manuscriptTypes: ["clinical_study"],
    sections: ["abstract", "introduction", "methods", "results", "discussion"],
    bindings: [
      {
        bindingKind: "general_package",
        bindingTargetId: "general-module-seeded-2",
        bindingTargetLabel: "缩略语与术语首现释义",
      },
    ],
    createdAt: "2026-03-31T07:57:05.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-general-front-matter-1",
    title: "作者单位与通讯作者前置信息规则",
    canonicalText: "作者顺序、单位序号、通讯作者与基金脚注应在首页信息块中保持一致且可核对。",
    summary: "默认绑定到通用包“作者单位与通讯作者前置信息”，用于首页结构核对。",
    knowledgeKind: "checklist",
    moduleScope: "editing",
    manuscriptTypes: ["clinical_study", "review", "case_report"],
    sections: ["front_matter"],
    bindings: [
      {
        bindingKind: "general_package",
        bindingTargetId: "general-module-seeded-3",
        bindingTargetLabel: "作者单位与通讯作者前置信息",
      },
    ],
    createdAt: "2026-03-31T07:57:20.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-general-abstract-keyword-1",
    title: "摘要标签与关键词规范规则",
    canonicalText: "临床研究摘要应使用统一标签，关键词数量、顺序与分隔符应符合模板要求。",
    summary: "默认绑定到通用包“摘要标签与关键词规范”，用于摘要与关键词区块统一。",
    knowledgeKind: "rule",
    moduleScope: "editing",
    manuscriptTypes: ["clinical_study"],
    sections: ["abstract", "keywords"],
    bindings: [
      {
        bindingKind: "general_package",
        bindingTargetId: "general-module-seeded-4",
        bindingTargetLabel: "摘要标签与关键词规范",
      },
    ],
    createdAt: "2026-03-31T07:57:35.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-general-structure-1",
    title: "临床研究章节结构主线规则",
    canonicalText: "临床研究稿件应至少能定位目标、方法、结果、结论与伦理信息，并保持章节顺序稳定。",
    summary: "默认绑定到通用包“标题层级与章节顺序”，用于筛查和后续结构统一。",
    knowledgeKind: "checklist",
    moduleScope: "screening",
    manuscriptTypes: ["clinical_study"],
    sections: ["body"],
    riskTags: ["structure"],
    bindings: [
      {
        bindingKind: "general_package",
        bindingTargetId: "general-module-seeded-5",
        bindingTargetLabel: "标题层级与章节顺序",
      },
    ],
    createdAt: "2026-03-31T07:57:50.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-general-table-format-1",
    title: "三线表与表注格式规则",
    canonicalText: "三线表应满足表题置上、表注置下、单位完整且统计学脚注与正文一致。",
    summary: "默认绑定到通用包“三线表与表注格式”，用于编辑和校对阶段的表格规范复用。",
    knowledgeKind: "checklist",
    moduleScope: "proofreading",
    manuscriptTypes: ["clinical_study"],
    sections: ["results"],
    riskTags: ["table-proofreading"],
    bindings: [
      {
        bindingKind: "general_package",
        bindingTargetId: "general-module-seeded-6",
        bindingTargetLabel: "三线表与表注格式",
      },
    ],
    createdAt: "2026-03-31T07:58:05.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-medical-ethics-1",
    title: "伦理声明完整性核查",
    canonicalText: "涉及人体研究时，伦理批件号、伦理委员会名称与知情同意说明必须齐全。",
    summary: "默认绑定到医学专用包“伦理声明核查”，用于高风险筛查与校对复核。",
    knowledgeKind: "rule",
    moduleScope: "screening",
    manuscriptTypes: ["clinical_study", "case_report"],
    sections: ["ethics", "methods", "back_matter"],
    riskTags: ["ethics"],
    bindings: [
      {
        bindingKind: "medical_package",
        bindingTargetId: "medical-module-seeded-1",
        bindingTargetLabel: "伦理声明核查",
      },
    ],
    createdAt: "2026-03-31T07:57:35.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-medical-endpoint-1",
    title: "终点与统计口径一致性核对",
    canonicalText: "主要终点名称、统计方法、分析人群、P 值与结果表述必须在摘要、方法、结果之间保持一致。",
    summary: "默认绑定到医学专用包“终点与统计口径核对”，用于临床研究主线高风险核查。",
    knowledgeKind: "rule",
    moduleScope: "screening",
    manuscriptTypes: ["clinical_study"],
    sections: ["abstract", "methods", "results", "discussion"],
    riskTags: ["statistics"],
    bindings: [
      {
        bindingKind: "medical_package",
        bindingTargetId: "medical-module-seeded-2",
        bindingTargetLabel: "终点与统计口径核对",
      },
    ],
    createdAt: "2026-03-31T07:58:05.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-medical-study-design-1",
    title: "研究设计与纳排标准规则",
    canonicalText: "临床研究需明确研究类型、纳入排除标准、分组方法、样本来源与随访窗口。",
    summary: "默认绑定到医学专用包“研究设计与纳排标准核查”，用于筛查阶段的主线判断。",
    knowledgeKind: "checklist",
    moduleScope: "screening",
    manuscriptTypes: ["clinical_study"],
    sections: ["methods"],
    riskTags: ["study-design"],
    bindings: [
      {
        bindingKind: "medical_package",
        bindingTargetId: "medical-module-seeded-3",
        bindingTargetLabel: "研究设计与纳排标准核查",
      },
    ],
    createdAt: "2026-03-31T07:58:50.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-medical-baseline-consistency-1",
    title: "基线特征与分组一致性规则",
    canonicalText: "样本量、组别命名、基线特征表与正文引用必须一致，不能出现表文冲突。",
    summary: "默认绑定到医学专用包“基线特征与分组一致性核查”，用于表文一致性复核。",
    knowledgeKind: "checklist",
    moduleScope: "proofreading",
    manuscriptTypes: ["clinical_study"],
    sections: ["results"],
    riskTags: ["consistency", "table"],
    bindings: [
      {
        bindingKind: "medical_package",
        bindingTargetId: "medical-module-seeded-4",
        bindingTargetLabel: "基线特征与分组一致性核查",
      },
    ],
    createdAt: "2026-03-31T07:59:05.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  {
    assetId: "knowledge-medical-safety-1",
    title: "不良事件与安全性表述规则",
    canonicalText: "不良事件、安全性结果与风险提示必须与正文结果一致，不能弱化或遗漏重要安全信息。",
    summary: "默认绑定到医学专用包“不良事件与安全性表述核查”，用于筛查与校对阶段复核。",
    knowledgeKind: "rule",
    moduleScope: "proofreading",
    manuscriptTypes: ["clinical_study"],
    sections: ["results", "discussion", "back_matter"],
    riskTags: ["safety"],
    bindings: [
      {
        bindingKind: "medical_package",
        bindingTargetId: "medical-module-seeded-5",
        bindingTargetLabel: "不良事件与安全性表述核查",
      },
    ],
    createdAt: "2026-03-31T07:59:20.000Z",
    updatedAt: BASELINE_UPDATED_AT,
  },
  ];

export const SEEDED_CLINICAL_STUDY_RULE_SETS: readonly EditorialRuleSetRecord[] = [
  {
    id: "rule-set-screening-1",
    template_family_id: "family-seeded-1",
    module: "screening",
    version_no: 1,
    status: "published",
  },
  {
    id: "rule-set-editing-1",
    template_family_id: "family-seeded-1",
    module: "editing",
    version_no: 1,
    status: "published",
  },
  {
    id: "rule-set-proofreading-1",
    template_family_id: "family-seeded-1",
    module: "proofreading",
    version_no: 1,
    status: "published",
  },
];

export const SEEDED_CLINICAL_STUDY_RULES: readonly EditorialRuleRecord[] = [
  {
    id: "rule-screening-ethics-1",
    rule_set_id: "rule-set-screening-1",
    order_no: 10,
    priority: 300,
    rule_object: "statement",
    rule_type: "content",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["methods", "ethics", "back_matter"],
      object_granularity: ["statement"],
    },
    selector: {
      statement_selector: {
        statement_kind: "ethics",
      },
    },
    trigger: {
      kind: "required_statement",
      statement_kind: "ethics",
    },
    action: {
      kind: "inspect_required_statement",
      placement: "methods_or_ethics",
      required_fields: ["approval_no", "committee_name", "informed_consent"],
    },
    authoring_payload: {
      baseline_key: "clinical_study_ethics_statement",
      linked_module_ids: ["medical-module-seeded-1"],
      linked_knowledge_item_ids: ["knowledge-medical-ethics-1"],
    },
    explanation_payload: {
      rationale: "人体研究必须能追溯伦理批准与知情同意信息。",
      applies_when: ["稿件涉及人体受试者、患者资料或干预研究。"],
      not_applies_when: ["明确为伦理豁免且已说明豁免原因。"],
      review_prompt: "核对伦理批件号、伦理委员会名称与知情同意说明是否齐全。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "error",
    enabled: true,
    manual_review_reason_template: "伦理与知情同意属于高风险内容，需人工复核。",
  },
  {
    id: "rule-screening-structure-1",
    rule_set_id: "rule-set-screening-1",
    order_no: 20,
    priority: 260,
    rule_object: "manuscript_structure",
    rule_type: "content",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["body"],
      object_granularity: ["section"],
    },
    selector: {
      manuscript_structure_selector: {
        manuscript_type: "clinical_study",
      },
    },
    trigger: {
      kind: "section_order",
      manuscript_type: "clinical_study",
    },
    action: {
      kind: "inspect_manuscript_structure",
      required_sections: ["objective", "methods", "results", "conclusion", "ethics"],
      section_order: ["objective", "methods", "results", "conclusion", "ethics"],
    },
    authoring_payload: {
      baseline_key: "clinical_study_structure",
      linked_module_ids: ["general-module-seeded-5"],
      linked_knowledge_item_ids: ["knowledge-general-structure-1"],
    },
    explanation_payload: {
      rationale: "临床研究主线章节缺失会直接影响筛查判断与后续治理绑定。",
      review_prompt: "确认目标、方法、结果、结论与伦理信息都能在章节结构中定位。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "error",
    enabled: true,
    manual_review_reason_template: "章节结构缺失或顺序异常会影响主线判断，需人工复核。",
  },
  {
    id: "rule-screening-design-1",
    rule_set_id: "rule-set-screening-1",
    order_no: 30,
    priority: 240,
    rule_object: "statement",
    rule_type: "content",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["methods"],
      object_granularity: ["paragraph"],
    },
    selector: {
      statement_selector: {
        statement_kind: "study_design",
      },
    },
    trigger: {
      kind: "required_statement",
      statement_kind: "study_design",
    },
    action: {
      kind: "inspect_required_statement",
      placement: "methods",
      required_fields: ["study_type", "inclusion_criteria", "exclusion_criteria", "grouping"],
    },
    authoring_payload: {
      baseline_key: "clinical_study_design",
      linked_module_ids: ["medical-module-seeded-3"],
      linked_knowledge_item_ids: ["knowledge-medical-study-design-1"],
    },
    explanation_payload: {
      rationale: "研究设计与纳排标准不完整时，AI 不应自行补全医学事实。",
      review_prompt: "核对研究类型、纳排标准、分组与样本来源是否完整。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "error",
    enabled: true,
    manual_review_reason_template: "研究设计与纳排标准属于高风险结构信息，需人工复核。",
  },
  {
    id: "rule-screening-endpoint-1",
    rule_set_id: "rule-set-screening-1",
    order_no: 40,
    priority: 220,
    rule_object: "statistical_expression",
    rule_type: "content",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["abstract", "methods", "results"],
      object_granularity: ["paragraph"],
    },
    selector: {
      section_selector: "results",
      pattern_selector: {
        content_class: "statistical_expression",
      },
    },
    trigger: {
      kind: "structural_presence",
      field: "primary_endpoint",
    },
    action: {
      kind: "inspect_statistical_alignment",
      aligned_sections: ["abstract", "methods", "results"],
      required_fields: ["primary_endpoint", "analysis_population", "p_value"],
    },
    authoring_payload: {
      baseline_key: "clinical_study_endpoint_statistics",
      linked_module_ids: ["medical-module-seeded-2"],
      linked_knowledge_item_ids: ["knowledge-medical-endpoint-1"],
    },
    explanation_payload: {
      rationale: "终点与统计口径不一致会直接影响医学结论有效性。",
      review_prompt: "核对主要终点、分析人群、统计方法与 P 值是否跨章节一致。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "error",
    enabled: true,
    manual_review_reason_template: "终点与统计口径冲突属于高风险结论问题，需人工复核。",
  },
  {
    id: "rule-editing-author-line-1",
    rule_set_id: "rule-set-editing-1",
    order_no: 10,
    priority: 180,
    rule_object: "author_line",
    rule_type: "format",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["front_matter"],
      object_granularity: ["author_line"],
    },
    selector: {
      section_selector: "front_matter",
      block_selector: "author_line",
    },
    trigger: {
      kind: "author_line_pattern",
      separator: "、",
    },
    action: {
      kind: "inspect_author_line",
      affiliation_format: "superscript_marker",
      corresponding_author_rule: "required",
    },
    authoring_payload: {
      baseline_key: "clinical_study_front_matter",
      linked_module_ids: ["general-module-seeded-3"],
      linked_knowledge_item_ids: ["knowledge-general-front-matter-1"],
    },
    explanation_payload: {
      rationale: "作者与单位信息涉及署名与责任归属，只能做结构核对。",
      review_prompt: "核对作者顺序、单位序号、通讯作者与基金标注是否一致。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "warning",
    enabled: true,
    manual_review_reason_template: "署名与单位信息涉及归属风险，需人工确认后落地。",
  },
  {
    id: "rule-editing-abstract-1",
    rule_set_id: "rule-set-editing-1",
    order_no: 20,
    priority: 160,
    rule_object: "abstract",
    rule_type: "format",
    execution_mode: "apply_and_inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["abstract"],
      object_granularity: ["heading"],
    },
    selector: {
      section_selector: "abstract",
      label_selector: {
        text: "摘要 目的",
      },
    },
    trigger: {
      kind: "exact_text",
      text: "摘要 目的",
    },
    action: {
      kind: "replace_heading",
      to: "摘要：目的",
    },
    authoring_payload: {
      baseline_key: "clinical_study_abstract_heading",
      linked_module_ids: ["general-module-seeded-4"],
      linked_knowledge_item_ids: ["knowledge-general-abstract-keyword-1"],
    },
    explanation_payload: {
      rationale: "摘要标签统一可提升编辑结果稳定性，并为后续校对提供固定锚点。",
      review_prompt: "确认摘要标签格式与关键词块口径一致。",
    },
    evidence_level: "medium",
    confidence_policy: "always_auto",
    severity: "warning",
    enabled: true,
    example_before: "摘要 目的",
    example_after: "摘要：目的",
  },
  {
    id: "rule-editing-terminology-1",
    rule_set_id: "rule-set-editing-1",
    order_no: 30,
    priority: 150,
    rule_object: "terminology",
    rule_type: "format",
    execution_mode: "apply_and_inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["abstract", "methods", "results", "discussion"],
      object_granularity: ["paragraph"],
    },
    selector: {
      pattern_selector: {
        content_class: "terminology",
      },
    },
    trigger: {
      kind: "terminology_variant",
      disallowed_variant: "稿内非标准术语",
    },
    action: {
      kind: "replace_terminology",
      preferred_term: "知识库标准术语",
    },
    authoring_payload: {
      baseline_key: "clinical_study_terminology",
      linked_module_ids: ["general-module-seeded-2"],
      linked_knowledge_item_ids: ["knowledge-general-abbreviation-1"],
    },
    explanation_payload: {
      rationale: "术语和缩略语统一是提升编辑一致性的主线基础能力。",
      review_prompt: "确认术语替换不会改变医学含义。",
    },
    evidence_level: "medium",
    confidence_policy: "high_confidence_only",
    severity: "warning",
    enabled: true,
    manual_review_reason_template: "术语替换可能影响医学语义，低置信度时需人工复核。",
  },
  {
    id: "rule-editing-heading-1",
    rule_set_id: "rule-set-editing-1",
    order_no: 40,
    priority: 140,
    rule_object: "heading_hierarchy",
    rule_type: "format",
    execution_mode: "apply_and_inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["body"],
      object_granularity: ["heading"],
    },
    selector: {
      section_selector: "body",
      block_selector: "heading",
    },
    trigger: {
      kind: "structural_presence",
      field: "heading",
    },
    action: {
      kind: "normalize_heading_hierarchy",
      sequence: "clinical_study_mainline",
    },
    authoring_payload: {
      baseline_key: "clinical_study_heading_hierarchy",
      linked_module_ids: ["general-module-seeded-5"],
      linked_knowledge_item_ids: ["knowledge-general-structure-1"],
    },
    explanation_payload: {
      rationale: "固定标题层级可减少编辑结果漂移，并便于后续残差定位。",
      review_prompt: "确认标题层级调整没有改变章节语义。",
    },
    evidence_level: "medium",
    confidence_policy: "high_confidence_only",
    severity: "warning",
    enabled: true,
  },
  {
    id: "rule-editing-reference-1",
    rule_set_id: "rule-set-editing-1",
    order_no: 50,
    priority: 130,
    rule_object: "reference",
    rule_type: "format",
    execution_mode: "apply_and_inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["reference"],
      object_granularity: ["reference_entry"],
    },
    selector: {
      section_selector: "reference",
      block_selector: "reference_entry",
    },
    trigger: {
      kind: "structural_presence",
      field: "reference",
    },
    action: {
      kind: "normalize_reference_entry",
      citation_style: "journal_managed",
    },
    authoring_payload: {
      baseline_key: "clinical_study_reference_format",
      linked_module_ids: ["general-module-seeded-1"],
      linked_knowledge_item_ids: ["knowledge-general-reference-1"],
    },
    explanation_payload: {
      rationale: "参考文献格式统一是高频、可复用且可追踪的编辑资产。",
      review_prompt: "确认著录信息与原始文献一致，避免自动补造字段。",
    },
    evidence_level: "medium",
    confidence_policy: "high_confidence_only",
    severity: "warning",
    enabled: true,
    manual_review_reason_template: "原始文献信息不完整时不能自动补齐，需人工复核。",
  },
  {
    id: "rule-table-editing-1",
    rule_set_id: "rule-set-editing-1",
    order_no: 60,
    priority: 120,
    rule_object: "table",
    rule_type: "format",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["results"],
      object_granularity: ["table"],
    },
    selector: {
      semantic_target: "header_cell",
      header_path_includes: ["Treatment group", "n (%)"],
    },
    trigger: {
      kind: "table_shape",
      layout: "three_line_table",
    },
    action: {
      kind: "inspect_table_rule",
      caption_requirement: "表题置于表上",
      layout_requirement: "三线表且单位、统计学脚注完整",
    },
    authoring_payload: {
      baseline_key: "clinical_study_three_line_table",
      linked_module_ids: ["general-module-seeded-6"],
      linked_knowledge_item_ids: ["knowledge-general-table-format-1"],
    },
    explanation_payload: {
      rationale: "表格格式和单位脚注是后续校对最常见的高频问题入口。",
      review_prompt: "核对表题位置、列头单位与统计学脚注是否完整。",
    },
    evidence_level: "medium",
    confidence_policy: "manual_only",
    severity: "warning",
    enabled: true,
    manual_review_reason_template: "表格结构和单位脚注需人工复核后才能落地。",
  },
  {
    id: "rule-proofreading-statistics-1",
    rule_set_id: "rule-set-proofreading-1",
    order_no: 10,
    priority: 260,
    rule_object: "statistical_expression",
    rule_type: "format",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["abstract", "results", "discussion"],
      object_granularity: ["paragraph"],
    },
    selector: {
      pattern_selector: {
        content_class: "statistical_expression",
      },
    },
    trigger: {
      kind: "statistical_unit_consistency",
      field: "statistical_expression",
    },
    action: {
      kind: "inspect_statistical_expression",
      unit_requirement: "same_as_table_and_text",
      p_value_format: "journal_managed",
    },
    authoring_payload: {
      baseline_key: "clinical_study_statistics_proofreading",
      linked_module_ids: ["medical-module-seeded-2"],
      linked_knowledge_item_ids: ["knowledge-medical-endpoint-1"],
    },
    explanation_payload: {
      rationale: "校对阶段最需要拦截统计单位、P 值与结果表述的残差错误。",
      review_prompt: "核对单位、P 值、统计学符号与方法结果口径是否一致。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "error",
    enabled: true,
    manual_review_reason_template: "统计学表达涉及高风险残差，需人工复核。",
  },
  {
    id: "rule-proofreading-baseline-table-1",
    rule_set_id: "rule-set-proofreading-1",
    order_no: 20,
    priority: 240,
    rule_object: "table",
    rule_type: "format",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["results"],
      object_granularity: ["table", "table_cell"],
    },
    selector: {
      semantic_target: "data_cell",
      header_path_includes: ["Baseline characteristics", "n (%)"],
    },
    trigger: {
      kind: "table_shape",
      layout: "three_line_table",
    },
    action: {
      kind: "inspect_table_rule",
      layout_requirement: "组别命名、样本量、单位与统计注释一致",
      cross_check_targets: ["methods_sample_size", "results_table", "results_text"],
    },
    authoring_payload: {
      baseline_key: "clinical_study_baseline_consistency",
      linked_module_ids: ["medical-module-seeded-4"],
      linked_knowledge_item_ids: ["knowledge-medical-baseline-consistency-1"],
    },
    explanation_payload: {
      rationale: "表文一致性是校对阶段最适合做残差沉淀与人工回流的高价值场景。",
      review_prompt: "核对样本量、组别命名、单位和表文引用是否一致。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "error",
    enabled: true,
    manual_review_reason_template: "基线表与正文不一致时会影响结论可信度，需人工复核。",
  },
  {
    id: "rule-proofreading-reference-1",
    rule_set_id: "rule-set-proofreading-1",
    order_no: 30,
    priority: 180,
    rule_object: "reference",
    rule_type: "format",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["reference", "discussion"],
      object_granularity: ["reference_entry", "citation"],
    },
    selector: {
      section_selector: "reference",
      block_selector: "reference_entry",
    },
    trigger: {
      kind: "structural_presence",
      field: "reference",
    },
    action: {
      kind: "inspect_reference_alignment",
      citation_style: "journal_managed",
      cross_check_text_citations: true,
    },
    authoring_payload: {
      baseline_key: "clinical_study_reference_proofreading",
      linked_module_ids: ["general-module-seeded-1"],
      linked_knowledge_item_ids: ["knowledge-general-reference-1"],
    },
    explanation_payload: {
      rationale: "校对阶段要确保正文引用与参考文献列表仍然一致。",
      review_prompt: "核对正文引用、参考文献顺序与著录信息是否一致。",
    },
    evidence_level: "medium",
    confidence_policy: "manual_only",
    severity: "warning",
    enabled: true,
  },
  {
    id: "rule-proofreading-safety-1",
    rule_set_id: "rule-set-proofreading-1",
    order_no: 40,
    priority: 230,
    rule_object: "statement",
    rule_type: "content",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["results", "discussion", "back_matter"],
      object_granularity: ["statement"],
    },
    selector: {
      statement_selector: {
        statement_kind: "safety",
      },
    },
    trigger: {
      kind: "required_statement",
      statement_kind: "safety",
    },
    action: {
      kind: "inspect_required_statement",
      placement: "results_or_discussion",
      required_fields: ["adverse_events", "serious_adverse_events", "risk_statement"],
    },
    authoring_payload: {
      baseline_key: "clinical_study_safety_statement",
      linked_module_ids: ["medical-module-seeded-5"],
      linked_knowledge_item_ids: ["knowledge-medical-safety-1"],
    },
    explanation_payload: {
      rationale: "安全性与不良事件属于校对阶段必须保守处理的高风险内容。",
      review_prompt: "核对不良事件、安全性结果与风险提示是否完整且不被弱化。",
    },
    evidence_level: "high",
    confidence_policy: "manual_only",
    severity: "error",
    enabled: true,
    manual_review_reason_template: "安全性与不良事件表述属于高风险内容，需人工复核。",
  },
  {
    id: "rule-table-proofreading-1",
    rule_set_id: "rule-set-proofreading-1",
    order_no: 50,
    priority: 170,
    rule_object: "table",
    rule_type: "format",
    execution_mode: "inspect",
    scope: {
      manuscript_types: ["clinical_study"],
      sections: ["results"],
      object_granularity: ["table"],
    },
    selector: {
      semantic_target: "header_cell",
      header_path_includes: ["Treatment group", "n (%)"],
    },
    trigger: {
      kind: "table_shape",
      layout: "three_line_table",
    },
    action: {
      kind: "inspect_table_rule",
      caption_requirement: "表题置于表上",
      layout_requirement: "表注置于表下且统计学脚注完整",
    },
    authoring_payload: {
      baseline_key: "clinical_study_table_proofreading",
      linked_module_ids: ["general-module-seeded-6"],
      linked_knowledge_item_ids: ["knowledge-general-table-format-1"],
    },
    explanation_payload: {
      rationale: "三线表格式残差是校对阶段最容易沉淀为规则与知识的高频场景。",
      review_prompt: "核对表题、表注、单位与统计学脚注是否符合模板要求。",
    },
    evidence_level: "medium",
    confidence_policy: "manual_only",
    severity: "warning",
    enabled: true,
    manual_review_reason_template: "表格结构与表注位置需人工复核后才能落地。",
  },
];
